import { Product } from "./types/Product.ts";

export const sampleProducts: Product[] = [
  {
    _id: "1",
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    image: "/images/shoes.jpg",
    category: "Shirts",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "2",
    name: "Adidas Fit Shirt",
    slug: "adidas-fit-shirt",
    image: "/images/shoes.jpg",
    category: "Shirts",
    brand: "Nike",
    price: 100,
    countInStock: 20,
    description: "High Quality Product",
    rating: 4.0,
    numReviews: 10,
  },
  {
    _id: "3",
    name: "Lacoste Free Pants",
    slug: "lacoste-free-pants",
    image: "/images/shoes.jpg",
    category: "Pants",
    brand: "Lacoste",
    price: 220,
    countInStock: 0,
    description: "High Quality Product",
    rating: 4.8,
    numReviews: 17,
  },
  {
    _id: "4",
    name: "Nike Slim Pant",
    slug: "nike-slim-pants",
    image: "/images/shoes.jpg",
    category: "Pants",
    brand: "Lacoste",
    price: 78,
    countInStock: 15,
    description: "High Quality Product",
    rating: 4.5,
    numReviews: 14,
  },
];
